[package]
edition = "2021"
name = "isometric"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_ecs_tilemap = "0.6.0"
bevy_rapier2d = {version = "0.15.0"}
getrandom = {version = "0.2", features = ["js"]}# Works with rand to support browser runder numbers
rand = "0.8"
